export default function country (code) {
    const iso = {
        AC:"ASCENSION ISLAND	",
        AF:"AFGHANISTAN	",
        AX:"ALAND	",
        AL:"ALBANIA	",
        DZ:"ALGERIA	",
        AD:"ANDORRA	",
        AO:"ANGOLA	",
        AI:"ANGUILLA	",
        AQ:"ANTARCTICA	",
        AG:"ANTIGUA AND BARBUDA	",
        AR:"ARGENTINA ",
        AM:"ARMENIA	",
        AW:"ARUBA	",
        AU:"AUSTRALIA	",
        AT:"AUSTRIA	",
        AZ:"AZERBAIJAN	",
        BS:"BAHAMAS	",
        BH:"BAHRAIN	",
        BD:"BANGLADESH	",
        BB:"BARBADOS	",
        BY:"BELARUS	",
        BE:"BELGIUM	",
        BZ:"BELIZE	",
        BJ:"BENIN	",
        BM:"BERMUDA	",
        BT:"BHUTAN	",
        BO:"BOLIVIA	",
        BA:"BOSNIA AND HERZEGOVINA	",
        BW:"BOTSWANA	",
        BV:"BOUVET ISLAND	",
        BR:"BRAZIL	",
        IO:"BRITISH INDIAN OCEAN TERR	",
        VG:"BRITISH VIRGIN ISLANDS	",
        BN:"BRUNEI DARUSSALAM	",
        BG:"BULGARIA	",
        BF:"BURKINA FASO	",
        BI:"BURUNDI	",
        KH:"CAMBODIA	",
        CM:"CAMEROON	",
        CA:"CANADA	",
        CV:"CAPE VERDE	",
        KY:"CAYMAN ISLANDS	",
        CF:"CENTRAL AFRICAN REPUBLIC	",
        TD:"CHAD	",
        CL:"CHILE	",
        CN:"PEOPLE’S REPUBLIC OF CHINA	",
        CX:"CHRISTMAS ISLANDS	",
        CC:"COCOS ISLANDS	",
        CO:"COLOMBIA	",
        KM:"COMORAS	",
        CG:"CONGO	",
        CD:"CONGO	",
        CK:"COOK ISLANDS	",
        CR:"COSTA RICA	",
        CI:"COTE D IVOIRE	",
        HR:"CROATIA	",
        CU:"CUBA	",
        CY:"CYPRUS	",
        CZ:"CZECH REPUBLIC	",
        DK:"DENMARK	",
        DJ:"DJIBOUTI	",
        DM:"DOMINICA	",
        DO:"DOMINICAN REPUBLIC	",
        TP:"EAST TIMOR	",
        EC:"ECUADOR	",
        EG:"EGYPT	",
        SV:"EL SALVADOR	",
        GQ:"EQUATORIAL GUINEA	",
        EE:"ESTONIA	",
        ET:"ETHIOPIA	",
        FK:"FALKLAND ISLANDS	",
        FO:"FAROE ISLANDS	",
        FJ:"FIJI	",
        FI:"FINLAND	",
        FR:"FRANCE	",
        FX:"FRANCE METROPOLITAN	",
        GF:"FRENCH GUIANA	",
        PF:"FRENCH POLYNESIA	",
        TF:"FRENCH SOUTHERN TERRITORIES	",
        GA:"GABON	",
        GM:"GAMBIA	",
        GE:"GEORGIA	",
        DE:"GERMANY	",
        GH:"GHANA	",
        GI:"GIBRALTAR	",
        GR:"GREECE	",
        GL:"GREENLAND	",
        GD:"GRENADA	",
        GP:"GUADELOUPE	",
        GU:"GUAM	",
        GT:"GUATEMALA	",
        GN:"GUINEA	",
        GW:"GUINEA-BISSAU	",
        GY:"GUYANA	",
        HT:"HAITI	",
        HM:"HEARD & MCDONALD ISLAND	",
        HN:"HONDURAS	",
        HK:"HONG KONG	",
        HU:"HUNGARY	",
        IS:"ICELAND	",
        IN:"INDIA	",
        ID:"INDONESIA	",
        IR:"IRAN	",
        IQ:"IRAQ	",
        IE:"IRELAND	",
        IM:"ISLE OF MAN	",
        IL:"ISRAEL	",
        IT:"ITALY	",
        JM:"JAMAICA	",
        JP:"JAPAN	",
        JO:"JORDAN	",
        KZ:"KAZAKHSTAN	",
        KE:"KENYA	",
        KI:"KIRIBATI	",
        KP:"North KOREA ",
        KR:"South KOREA "  ,
        KW:"KUWAIT	",
        KG:"KYRGYZSTAN	",
        LA:"LAO PEOPLE’S DEM. REPUBLIC	",
        LV:"LATVIA	",
        LB:"LEBANON	",
        LS:"LESOTHO	",
        LR:"LIBERIA	",
        LY:"LIBYAN ARAB JAMAHIRIYA	",
        LI:"LIECHTENSTEIN	",
        LT:"LITHUANIA	",
        LU:"LUXEMBOURG	",
        MO:"MACAO	",
        MK:"MACEDONIA	",
        MG:"MADAGASCAR	",
        MW:"MALAWI	",
        MY:"MALAYSIA	",
        MV:"MALDIVES	",
        ML:"MALI	",
        MT:"MALTA	",
        MH:"MARSHALL ISLANDS	",
        MQ:"MARTINIQUE	",
        MR:"MAURITANIA	",
        MU:"MAURITIUS	",
        YT:"MAYOTTE	",
        MX:"MEXICO	",
        FM:"MICRONESIA	",
        MD:"MOLDAVA	",
        MC:"MONACO	",
        MN:"MONGOLIA	",
        ME:"MONTENEGRO	",
        MS:"MONTSERRAT	",
        MA:"MOROCCO	",
        MZ:"MOZAMBIQUE	",
        MM:"MYANMAR	",
        NA:"NAMIBIA	",
        NR:"NAURU	",
        NP:"NEPAL	",
        AN:"NETHERLANDS ANTILLES	",
        NL:"NETHERLANDS, THE	",
        NC:"NEW CALEDONIA	",
        NZ:"NEW ZEALAND	",
        NI:"NICARAGUA	",
        NE:"NIGER	",
        NG:"NIGERIA	",
        NU:"NIUE	",
        NF:"NORFOLK ISLAND	",
        MP:"NORTHERN MARIANA ISLANDS	",
        NO:"NORWAY	",
        OM:"OMAN	",
        PK:"PAKISTAN	",
        PW:"PALAU	",
        PS:"PALESTINE	",
        PA:"PANAMA	",
        PG:"PAPUA NEW GUINEA	",
        PY:"PARAGUAY	",
        PE:"PERU	",
        PH:"PHILIPPINES ",
        PN:"PITCAIRN	",
        PL:"POLAND	",
        PT:"PORTUGAL	",
        PR:"PUERTO RICO	",
        QA:"QATAR	",
        RE:"REUNION	",
        RO:"ROMANIA	",
        RU:"RUSSIAN ",
        RW:"RWANDA	",
        WS:"SAMOA	",
        SM:"SAN MARINO	",
        ST:"SAO TOME/PRINCIPE	",
        SA:"SAUDI ARABIA	",
        SN:"SENEGAL	",
        RS:"SERBIA	",
        SC:"SEYCHELLES	",
        SL:"SIERRA LEONE	",
        SG:"SINGAPORE	",
        SK:"SLOVAKIA	",
        SI:"SLOVENIA	",
        SB:"SOLOMON ISLANDS	",
        SO:"SOMALIA	",
        AS:"SOMOA	",
        ZA:"SOUTH AFRICA	",
        GS:"SOUTH GEORGIA	",
        SU:"SOVIET UNION	",
        ES:"SPAIN	",
        LK:"SRI LANKA	",
        SH:"ST. HELENA	",
        KN:"ST. KITTS AND NEVIS	",
        LC:"ST. LUCIA	",
        PM:"ST. PIERRE AND MIQUELON	",
        VC:"ST. VINCENT & THE GRENADINES	",
        SD:"SUDAN	",
        SR:"SURINAME	",
        SJ:"SVALBARD AND JAN MAYEN	",
        SZ:"SWAZILAND	",
        SE:"SWEDEN	",
        CH:"SWITZERLAND	",
        SY:"SYRIAN ARAB REPUBLIC	",
        TW:"TAIWAN	",
        TJ:"TAJIKISTAN	",
        TZ:"TANZANIA	",
        TH:"THAILAND	",
        TG:"TOGO	",
        TK:"TOKELAU	",
        TO:"TONGA	",
        TT:"TRINIDAD AND TOBAGO	",
        TN:"TUNISIA	",
        TR:"TURKEY	",
        TM:"TURKMENISTAN	",
        TC:"TURKS AND CAICOS ISLANDS	",
        TV:"TUVALU	",
        UG:"UGANDA	",
        UA:"UKRAINE	",
        AE:"UNITED ARAB EMIRATES	",
        GB:"UNITED KINGDOM ",
        UK:"UNITED KINGDOM	",
        US:"UNITED STATES	",
        UM:"UNITED STATES MINOR OUTL.IS.	",
        UY:"URUGUAY	",
        UZ:"UZBEKISTAN	",
        VU:"VANUATU	",
        VA:"VATICAN CITY STATE	",
        VE:"VENEZUELA	",
        VN:"VIETNAM	",
        VI:"VIRGIN ISLANDS	",
        WF:"WALLIS AND FUTUNA ISLANDS	",
        EH:"WESTERN SAHARA	",
        YE:"YEMEN	",
        ZM: "ZAMBIA	",
        ZW:"ZIMBABWE	"
    };

    return iso[code].trimEnd();
}
